---
- name: Linux Install Software using a role
  hosts: all
  gather_facts: true
  become: true
  roles:
    - rsoliman.performance_demos.linux_dnf_install_packages
    - rsoliman.performance_demos.linux_apply_common_config
    - rsoliman.performance_demos.linux_get_public_ip
    - rsoliman.performance_demos.linux_generate_packages_report
  tasks:
    - name: Install and configure Fluentd
      ansible.builtin.include_role:
        name: geerlingguy.fluentd

    - name: Install and configure Kibana
      ansible.builtin.include_role:
        name: geerlingguy.kibana
