---
- name: Linux Install Software using a role
  hosts: all
  gather_facts: true
  become: true
  roles:
    - rsoliman.performance_demos.linux_dnf_install_packages
    - rsoliman.performance_demos.linux_apply_common_config
    - rsoliman.performance_demos.linux_get_publicip
    - rsoliman.performance_demos.linux_generate_packages_report
  tasks:
    - name: Config sysctl
      ansible.builtin.include_role:
        name: rsoliman.performance_demos.linux_config_sysctl

    - name: Set MOTD
      ansible.builtin.include_role:
        name: rsoliman.performance_demos.linux_set_motd

    - name: Run post init Script
      ansible.builtin.include_role:
        name: rsoliman.performance_demos.linux_run_script
