---
- name: Linux Say Hello Several Times
  hosts: all
  gather_facts: true
  environment:
    ANSIBLE_STDOUT_CALLBACK: ansible.posix.debug
  tasks:
    - name: Ping
      ansible.builtin.ping:

    - name: Say hello with debug
      ansible.builtin.debug:
        msg: Hello!
        
    - name: Say hello with a command
      ansible.builtin.command: echo "hello"

    - name: Say hello with a shell
      ansible.builtin.shell: echo "hello"

    - name: Say hello with RAW
      ansible.builtin.raw: echo "hello"