namespace: rsoliman
name: performance_demos
version: 1.0.0
readme: README.md
authors:
- Raed Soliman <raedrizk@gmail.com>

description: A collection of roles used to demo the effects of changing settings on performance.

license:
- "MIT"

tags: ['performance','demo','ansible','raedrizk','rsoliman']

dependencies:
    "ansible.builtin": "*"

repository: http://example.com/repository
homepage: http://example.com
issues: http://example.com/issue/tracker
